/**
 * A Task's log stream, over server-sent events.
 *
 * R49, and it is the reason this file is not a `useQuery`: none of the three
 * upstreams streams a log -- all three expose it as polled REST -- so this is the
 * one place in the console where a progress signal has to be *pushed*, and a
 * poller dressed as streaming would be a worse answer than no answer, because
 * it would look like progress while the work was actually in flight.
 *
 * ## Why `EventSource` and not the generated call
 *
 * The document declares `TaskLogStream` as `text/event-stream`, and orval types
 * the generated `taskLogStream()` as a single `TaskLogEvent` -- because a
 * function's return type cannot express a stream, and the generated call reads
 * the body as JSON. So the console uses the *URL the generator built*
 * (`getTaskLogStreamUrl`, the same path and the same query parameters the
 * generated call would have sent) and hands it to a browser `EventSource`, which
 * is the client that can hold a response open. Nothing about the endpoint is
 * re-declared here: the path, the `Last-Event-ID` parameter and the shape of an
 * event all come from the document.
 *
 * ## What a malformed line does
 *
 * Nothing is dropped. A line that will not parse is kept as a **fault** in the
 * transcript, in the position it arrived, with the reason and the raw text --
 * because a provisioner emitting a line the console cannot read is exactly the
 * failure a log view exists to surface, and a screen that skipped it would show a
 * clean run over a broken one. What validates a line is the *document's own*
 * generated Zod schema, so "malformed" means "the contract rejects it" rather
 * than "this screen's idea of a field is out of date".
 *
 * ## How a dropped connection is survived
 *
 * Three facts, in order:
 *
 *  1. `seq` is the SSE event id, and it is monotonic from 1, so the console
 *     always knows the highest line it holds.
 *  2. On a drop the console closes the source and opens a *new* one with
 *     `Last-Event-ID` set to the highest `seq` it holds -- the query parameter
 *     the document declares for exactly this, so the resume is deliberate and
 *     visible in a URL rather than an invisible browser header.
 *  3. Lines already held are keyed by `seq`, so a control plane that replays
 *     from the beginning anyway -- which is the honest answer from a server that
 *     cannot seek -- loses nothing and duplicates nothing. The resume is an
 *     optimisation; the dedupe is the guarantee.
 *
 * The console owns the retry rather than leaning on the browser's implicit one,
 * for three reasons: it can show the operator which attempt it is on, it can
 * stop once a terminal state has been observed, and it can tell a *dropped*
 * stream (reconnect) from a *refused* one (a 4xx, which is terminal for an
 * `EventSource` and is offered as a control the operator can press again).
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { getTaskLogStreamUrl } from "@sovren/client";
import type { TaskLogEvent, TaskState } from "@sovren/client";

// The document's own validator for a log event, generated by orval into the
// client package. Reached by path for the same reason the mock backend reaches
// the fakes' handlers by path: `@sovren/client`'s `exports` map exposes `.`,
// `./generated` and `./models`, and none of them re-exports the model schemas.
// Widening that map is the tidier fix and belongs to whoever owns the package;
// recorded in the console's report rather than done here.
import { TaskLogEvent as TaskLogEventSchema } from "../../../../../client/src/generated/zod/taskLogEvent.zod";

/**
 * The base the generated client puts in front of every operation.
 *
 * `safe-fetch.ts` holds it privately and does not export it, so the one client
 * that cannot go through the generated mutator -- `EventSource`, which takes a
 * URL rather than a path -- repeats it. Worth exporting; recorded, not changed.
 */
const API_BASE = "/api/v1";

/** The first retry after a drop. Long enough not to spin, short enough to feel alive. */
const RETRY_BASE_MS = 500;

/** The ceiling on the backoff. A dropped stream is still worth retrying tomorrow. */
const RETRY_CEILING_MS = 30_000;

/**
 * Where a stream is, as far as the operator is concerned.
 *
 * `idle` is a Task that has emitted nothing, which is a real state (a `queued`
 * Task) rather than a stream that has not started. `refused` is a control plane
 * that answered with a status: the browser will not retry that on its own, so
 * the console says so and offers the control.
 */
export type StreamStatus = "idle" | "connecting" | "live" | "reconnecting" | "refused" | "closed";

/** A line the document's validator would not accept, kept rather than dropped. */
export interface StreamFault {
  /** Stable across renders, so a re-render does not renumber the transcript. */
  readonly key: string;
  /** The line as it arrived. */
  readonly raw: string;
  /** Why the contract rejects it. */
  readonly why: string;
}

/** One row of the transcript: an event, or a line the console could not read. */
export type LogEntry =
  | { readonly kind: "event"; readonly event: TaskLogEvent }
  | { readonly kind: "fault"; readonly fault: StreamFault };

export interface TaskLogStream {
  /** The transcript, in the order it arrived. */
  readonly entries: readonly LogEntry[];
  /** The highest `seq` held, which is what a resume asks to continue from. */
  readonly lastSeq: number | null;
  readonly status: StreamStatus;
  /** How many times the stream has been re-opened after a drop. */
  readonly attempts: number;
  /**
   * The `Last-Event-ID` the current connection was opened with, or null for a
   * first connection. Shown, because a resume nobody can see is a resume nobody
   * can trust.
   */
  readonly resumedFrom: number | null;
  /**
   * The terminal event, when one has been *received*.
   *
   * This is the only thing in the console that may be called an outcome, and it
   * is null until a `result` event actually crosses the wire. Not a timer, not
   * the shape of the log, not optimism: R44.
   */
  readonly result: TaskLogEvent | null;
  /** Stop the stream and keep every line. Used by cancel and by unmount. */
  readonly stop: () => void;
  /**
   * Open it again, resuming from the last `seq` held.
   *
   * Offered when the control plane *refused* the stream, because a refusal is the
   * one failure a browser will not retry and the one an operator can plausibly fix
   * -- the estate changed, the sentinel is gone.
   */
  readonly reopen: () => void;
}

export interface UseTaskLogStreamOptions {
  /** The ref from the path: an id, or the `id:target` form. Never a name. */
  readonly ref: string;
  /** How many events the control plane says it holds. Zero means there is nothing to stream. */
  readonly logCount: number;
  /** The `seq` of the last event it holds, or null when it holds none. */
  readonly lastSeq: number | null;
}

/** The states a Task can finish in. A `result` in any other state is not an outcome. */
const isTerminal = (state: TaskState | null | undefined): state is TaskState =>
  state === "succeeded" || state === "failed" || state === "cancelled";

/**
 * The stream's URL, from the generated path builder.
 *
 * `getTaskLogStreamUrl` is what `taskLogStream()` itself calls, so the path and
 * the `Last-Event-ID` parameter are the document's rather than a hand-written
 * string. The `Last-Event-ID` is a *query* parameter because the document
 * declares it as one for the deliberate resume; the browser also sends it as a
 * header on its own retries, and a control plane should honour either.
 */
export const taskLogStreamUrl = (ref: string, lastEventId: number | null): string => {
  const path = getTaskLogStreamUrl(
    ref,
    lastEventId === null ? undefined : { "Last-Event-ID": lastEventId },
  );
  return new URL(`${API_BASE}${path}`, globalThis.location.origin).toString();
};

/** Why the document's validator rejected a line, in one clause. */
const rejection = (error: {
  issues: readonly { path: PropertyKey[]; message: string }[];
}): string => {
  const first = error.issues[0];
  if (first === undefined) return "it is not a TaskLogEvent";
  const where = first.path.length === 0 ? "the event" : first.path.map(String).join(".");
  return `${where}: ${first.message}`;
};

/**
 * Read one line of the stream.
 *
 * A line is either an event the document accepts, or the reason it does not.
 * There is no third answer: a stream that cannot be parsed is not a reason to
 * show an operator a shorter log than the one that exists.
 */
const readLine = (raw: string): TaskLogEvent | { readonly why: string } => {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return { why: "it is not JSON" };
  }
  const checked = TaskLogEventSchema.safeParse(parsed);
  if (!checked.success) return { why: rejection(checked.error) };
  return checked.data as TaskLogEvent;
};

/** The tags a `TaskLogEvent` carries, and the event names the server sends them under. */
const TAGS: readonly TaskLogEvent["tag"][] = ["log", "step", "result"];

/**
 * Open a Task's log stream, and keep it open until there is a reason not to.
 *
 * The transcript lives in state because it is the screen's content; everything
 * else about the connection -- the `EventSource`, the retry timer, the set of
 * `seq`s already held, the resume point -- lives inside the effect, because all
 * of it is per-connection and none of it is anything a render should read.
 */
export function useTaskLogStream({
  ref,
  logCount,
  lastSeq,
}: UseTaskLogStreamOptions): TaskLogStream {
  const [entries, setEntries] = useState<readonly LogEntry[]>([]);
  const [status, setStatus] = useState<StreamStatus>("connecting");
  const [attempts, setAttempts] = useState(0);
  const [resumedFrom, setResumedFrom] = useState<number | null>(null);
  const [result, setResult] = useState<TaskLogEvent | null>(null);

  /** A different Task is a different transcript, so the old one goes. */
  useEffect(() => {
    setEntries([]);
    setResult(null);
  }, [ref]);

  /** The operator's stop, and the control that undoes it. */
  const [halted, setHalted] = useState(false);
  const [nonce, setNonce] = useState(0);
  const faultCount = useRef(0);

  useEffect(() => {
    if (halted) {
      setStatus("closed");
      return;
    }
    // A Task that has emitted nothing has no stream to open. The contract says
    // so in a fixed code, and an `EventSource` against it would sit there
    // reconnecting to a stream that will never carry anything.
    if (logCount === 0) {
      setStatus("idle");
      return;
    }

    /**
     * The `seq`s this console already holds.
     *
     * The dedupe is the guarantee, and the resume is the optimisation: a control
     * plane that honours `Last-Event-ID` sends only what is new, and one that
     * cannot seek replays from the start. Both are correct here.
     */
    const held = new Set<number>();
    let resume: number | null = null;
    let attempt = 0;
    let source: EventSource | null = null;
    let timer: ReturnType<typeof setTimeout> | null = null;
    let alive = true;

    const close = (next: StreamStatus) => {
      source?.close();
      source = null;
      if (alive) setStatus(next);
    };

    const open = (): void => {
      if (!alive) return;
      setStatus(attempt === 0 ? "connecting" : "reconnecting");
      setAttempts(attempt);
      setResumedFrom(resume);
      source = new EventSource(taskLogStreamUrl(ref, resume));

      source.onopen = () => {
        if (alive) setStatus("live");
      };

      const receive = (event: Event): void => {
        if (!alive) return;
        const message = event as MessageEvent<string>;
        const raw = typeof message.data === "string" ? message.data : String(message.data ?? "");
        const line = readLine(raw);

        if ("why" in line) {
          faultCount.current += 1;
          setEntries((current) => [
            ...current,
            {
              kind: "fault",
              fault: { key: `fault-${String(faultCount.current)}`, raw, why: line.why },
            },
          ]);
          return;
        }

        if (held.has(line.seq)) return;
        held.add(line.seq);
        resume = line.seq;
        setEntries((current) => [...current, { kind: "event", event: line }]);

        // A result is the outcome, and receiving it is the only thing that lets
        // the console name one.
        if (line.tag === "result" && isTerminal(line.state)) {
          setResult(line);
          close("closed");
          return;
        }
        // The control plane said which `seq` its last event carries. Holding that
        // one means the log is complete, which is a different fact from the work
        // having succeeded -- and a Task whose log ends without a `result` is
        // exactly the case where conflating them would be a lie.
        if (lastSeq !== null && line.seq >= lastSeq) close("closed");
      };

      for (const tag of TAGS) source.addEventListener(tag, receive);
      // A server that sends no event name is still an SSE server, and a browser
      // delivers those to `message`. Both listeners, so the console does not
      // depend on which the control plane chose.
      source.addEventListener("message", receive);

      source.onerror = () => {
        if (!alive) return;
        // `EventSource` reports a refused connection as CLOSED and a dropped one
        // as CONNECTING, and that is the whole difference between "the control
        // plane said no" and "the wire went away". Retrying a refusal is the
        // poller this file exists not to be.
        if (source?.readyState === 2 /* CLOSED */) {
          close("refused");
          return;
        }
        source?.close();
        source = null;
        attempt += 1;
        setStatus("reconnecting");
        setAttempts(attempt);
        const wait = Math.min(RETRY_BASE_MS * 2 ** (attempt - 1), RETRY_CEILING_MS);
        timer = setTimeout(() => {
          timer = null;
          open();
        }, wait);
      };
    };

    open();

    return () => {
      alive = false;
      if (timer !== null) clearTimeout(timer);
      source?.close();
    };
  }, [ref, logCount, lastSeq, halted, nonce]);

  const stop = useCallback(() => {
    setHalted(true);
  }, []);

  const reopen = useCallback(() => {
    faultCount.current = 0;
    setHalted(false);
    setNonce((value) => value + 1);
  }, []);

  /**
   * The highest `seq` held.
   *
   * The maximum rather than the last, so a stream that delivered a line out of
   * order -- which `seq` exists to make survivable -- still resumes from the
   * right place.
   */
  const held = entries.reduce<number | null>(
    (highest, entry) =>
      entry.kind === "event" && (highest === null || entry.event.seq > highest)
        ? entry.event.seq
        : highest,
    null,
  );

  return { entries, lastSeq: held, status, attempts, resumedFrom, result, stop, reopen };
}
