/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SiteRouteImport } from './routes/site'
import { Route as FleetIndexRouteImport } from './routes/fleet/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as SettingsConsoleRouteImport } from './routes/settings/console'
import { Route as SiteIndexRouteImport } from './routes/site/index'
import { Route as FleetNodesIndexRouteImport } from './routes/fleet/nodes/index'
import { Route as FleetPeersIndexRouteImport } from './routes/fleet/peers/index'
import { Route as FleetTasksIndexRouteImport } from './routes/fleet/tasks/index'
import { Route as FleetTasksTaskRouteImport } from './routes/fleet/tasks/$task'
import { Route as FleetVmsIndexRouteImport } from './routes/fleet/vms/index'
import { Route as FleetVmsNewRouteImport } from './routes/fleet/vms/new'
import { Route as SettingsConnectionsIndexRouteImport } from './routes/settings/connections/index'
import { Route as SettingsConnectionsConnectionRouteImport } from './routes/settings/connections/$connection'
import { Route as SiteSiteIndexRouteImport } from './routes/site/$site/index'
import { Route as FleetNodesNodeIndexRouteImport } from './routes/fleet/nodes/$node/index'
import { Route as FleetPeersPeerIndexRouteImport } from './routes/fleet/peers/$peer/index'
import { Route as FleetVmsVmIndexRouteImport } from './routes/fleet/vms/$vm/index'
import { Route as FleetVmsVmEditRouteImport } from './routes/fleet/vms/$vm/edit'
import { Route as SiteSiteNodesIndexRouteImport } from './routes/site/$site/nodes/index'
import { Route as SiteSitePeersIndexRouteImport } from './routes/site/$site/peers/index'
import { Route as SiteSiteVmsIndexRouteImport } from './routes/site/$site/vms/index'
import { Route as SiteSiteNodesNodeIndexRouteImport } from './routes/site/$site/nodes/$node/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FleetRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConsoleRoute = SettingsConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => SettingsRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const FleetNodesIndexRoute = FleetNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => FleetRoute,
} as any)
const FleetPeersIndexRoute = FleetPeersIndexRouteImport.update({
  id: '/peers/',
  path: '/peers/',
  getParentRoute: () => FleetRoute,
} as any)
const FleetTasksIndexRoute = FleetTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => FleetRoute,
} as any)
const FleetTasksTaskRoute = FleetTasksTaskRouteImport.update({
  id: '/tasks/$task',
  path: '/tasks/$task',
  getParentRoute: () => FleetRoute,
} as any)
const FleetVmsIndexRoute = FleetVmsIndexRouteImport.update({
  id: '/vms/',
  path: '/vms/',
  getParentRoute: () => FleetRoute,
} as any)
const FleetVmsNewRoute = FleetVmsNewRouteImport.update({
  id: '/vms/new',
  path: '/vms/new',
  getParentRoute: () => FleetRoute,
} as any)
const SettingsConnectionsIndexRoute =
  SettingsConnectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsConnectionsRoute,
  } as any)
const SettingsConnectionsConnectionRoute =
  SettingsConnectionsConnectionRouteImport.update({
    id: '/$connection',
    path: '/$connection',
    getParentRoute: () => SettingsConnectionsRoute,
  } as any)
const SiteSiteIndexRoute = SiteSiteIndexRouteImport.update({
  id: '/$site/',
  path: '/$site/',
  getParentRoute: () => SiteRoute,
} as any)
const FleetNodesNodeIndexRoute = FleetNodesNodeIndexRouteImport.update({
  id: '/nodes/$node/',
  path: '/nodes/$node/',
  getParentRoute: () => FleetRoute,
} as any)
const FleetPeersPeerIndexRoute = FleetPeersPeerIndexRouteImport.update({
  id: '/peers/$peer/',
  path: '/peers/$peer/',
  getParentRoute: () => FleetRoute,
} as any)
const FleetVmsVmIndexRoute = FleetVmsVmIndexRouteImport.update({
  id: '/vms/$vm/',
  path: '/vms/$vm/',
  getParentRoute: () => FleetRoute,
} as any)
const FleetVmsVmEditRoute = FleetVmsVmEditRouteImport.update({
  id: '/vms/$vm/edit',
  path: '/vms/$vm/edit',
  getParentRoute: () => FleetRoute,
} as any)
const SiteSiteNodesIndexRoute = SiteSiteNodesIndexRouteImport.update({
  id: '/$site/nodes/',
  path: '/$site/nodes/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSitePeersIndexRoute = SiteSitePeersIndexRouteImport.update({
  id: '/$site/peers/',
  path: '/$site/peers/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSiteVmsIndexRoute = SiteSiteVmsIndexRouteImport.update({
  id: '/$site/vms/',
  path: '/$site/vms/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSiteNodesNodeIndexRoute = SiteSiteNodesNodeIndexRouteImport.update({
  id: '/$site/nodes/$node/',
  path: '/$site/nodes/$node/',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fleet': typeof FleetRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/site': typeof SiteRouteWithChildren
  '/settings/connections': typeof SettingsConnectionsRouteWithChildren
  '/settings/console': typeof SettingsConsoleRoute
  '/fleet/': typeof FleetIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/site/': typeof SiteIndexRoute
  '/fleet/tasks/$task': typeof FleetTasksTaskRoute
  '/fleet/vms/new': typeof FleetVmsNewRoute
  '/settings/connections/$connection': typeof SettingsConnectionsConnectionRoute
  '/fleet/nodes/': typeof FleetNodesIndexRoute
  '/fleet/peers/': typeof FleetPeersIndexRoute
  '/fleet/tasks/': typeof FleetTasksIndexRoute
  '/fleet/vms/': typeof FleetVmsIndexRoute
  '/settings/connections/': typeof SettingsConnectionsIndexRoute
  '/site/$site/': typeof SiteSiteIndexRoute
  '/fleet/vms/$vm/edit': typeof FleetVmsVmEditRoute
  '/fleet/nodes/$node/': typeof FleetNodesNodeIndexRoute
  '/fleet/peers/$peer/': typeof FleetPeersPeerIndexRoute
  '/fleet/vms/$vm/': typeof FleetVmsVmIndexRoute
  '/site/$site/nodes/': typeof SiteSiteNodesIndexRoute
  '/site/$site/peers/': typeof SiteSitePeersIndexRoute
  '/site/$site/vms/': typeof SiteSiteVmsIndexRoute
  '/site/$site/nodes/$node/': typeof SiteSiteNodesNodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/console': typeof SettingsConsoleRoute
  '/fleet': typeof FleetIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/site': typeof SiteIndexRoute
  '/fleet/tasks/$task': typeof FleetTasksTaskRoute
  '/fleet/vms/new': typeof FleetVmsNewRoute
  '/settings/connections/$connection': typeof SettingsConnectionsConnectionRoute
  '/fleet/nodes': typeof FleetNodesIndexRoute
  '/fleet/peers': typeof FleetPeersIndexRoute
  '/fleet/tasks': typeof FleetTasksIndexRoute
  '/fleet/vms': typeof FleetVmsIndexRoute
  '/settings/connections': typeof SettingsConnectionsIndexRoute
  '/site/$site': typeof SiteSiteIndexRoute
  '/fleet/vms/$vm/edit': typeof FleetVmsVmEditRoute
  '/fleet/nodes/$node': typeof FleetNodesNodeIndexRoute
  '/fleet/peers/$peer': typeof FleetPeersPeerIndexRoute
  '/fleet/vms/$vm': typeof FleetVmsVmIndexRoute
  '/site/$site/nodes': typeof SiteSiteNodesIndexRoute
  '/site/$site/peers': typeof SiteSitePeersIndexRoute
  '/site/$site/vms': typeof SiteSiteVmsIndexRoute
  '/site/$site/nodes/$node': typeof SiteSiteNodesNodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fleet': typeof FleetRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/site': typeof SiteRouteWithChildren
  '/settings/connections': typeof SettingsConnectionsRouteWithChildren
  '/settings/console': typeof SettingsConsoleRoute
  '/fleet/': typeof FleetIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/site/': typeof SiteIndexRoute
  '/fleet/tasks/$task': typeof FleetTasksTaskRoute
  '/fleet/vms/new': typeof FleetVmsNewRoute
  '/settings/connections/$connection': typeof SettingsConnectionsConnectionRoute
  '/fleet/nodes/': typeof FleetNodesIndexRoute
  '/fleet/peers/': typeof FleetPeersIndexRoute
  '/fleet/tasks/': typeof FleetTasksIndexRoute
  '/fleet/vms/': typeof FleetVmsIndexRoute
  '/settings/connections/': typeof SettingsConnectionsIndexRoute
  '/site/$site/': typeof SiteSiteIndexRoute
  '/fleet/vms/$vm/edit': typeof FleetVmsVmEditRoute
  '/fleet/nodes/$node/': typeof FleetNodesNodeIndexRoute
  '/fleet/peers/$peer/': typeof FleetPeersPeerIndexRoute
  '/fleet/vms/$vm/': typeof FleetVmsVmIndexRoute
  '/site/$site/nodes/': typeof SiteSiteNodesIndexRoute
  '/site/$site/peers/': typeof SiteSitePeersIndexRoute
  '/site/$site/vms/': typeof SiteSiteVmsIndexRoute
  '/site/$site/nodes/$node/': typeof SiteSiteNodesNodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fleet'
    | '/settings'
    | '/site'
    | '/settings/connections'
    | '/settings/console'
    | '/fleet/'
    | '/settings/'
    | '/site/'
    | '/fleet/tasks/$task'
    | '/fleet/vms/new'
    | '/settings/connections/$connection'
    | '/fleet/nodes/'
    | '/fleet/peers/'
    | '/fleet/tasks/'
    | '/fleet/vms/'
    | '/settings/connections/'
    | '/site/$site/'
    | '/fleet/vms/$vm/edit'
    | '/fleet/nodes/$node/'
    | '/fleet/peers/$peer/'
    | '/fleet/vms/$vm/'
    | '/site/$site/nodes/'
    | '/site/$site/peers/'
    | '/site/$site/vms/'
    | '/site/$site/nodes/$node/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/console'
    | '/fleet'
    | '/settings'
    | '/site'
    | '/fleet/tasks/$task'
    | '/fleet/vms/new'
    | '/settings/connections/$connection'
    | '/fleet/nodes'
    | '/fleet/peers'
    | '/fleet/tasks'
    | '/fleet/vms'
    | '/settings/connections'
    | '/site/$site'
    | '/fleet/vms/$vm/edit'
    | '/fleet/nodes/$node'
    | '/fleet/peers/$peer'
    | '/fleet/vms/$vm'
    | '/site/$site/nodes'
    | '/site/$site/peers'
    | '/site/$site/vms'
    | '/site/$site/nodes/$node'
  id:
    | '__root__'
    | '/'
    | '/fleet'
    | '/settings'
    | '/site'
    | '/settings/connections'
    | '/settings/console'
    | '/fleet/'
    | '/settings/'
    | '/site/'
    | '/fleet/tasks/$task'
    | '/fleet/vms/new'
    | '/settings/connections/$connection'
    | '/fleet/nodes/'
    | '/fleet/peers/'
    | '/fleet/tasks/'
    | '/fleet/vms/'
    | '/settings/connections/'
    | '/site/$site/'
    | '/fleet/vms/$vm/edit'
    | '/fleet/nodes/$node/'
    | '/fleet/peers/$peer/'
    | '/fleet/vms/$vm/'
    | '/site/$site/nodes/'
    | '/site/$site/peers/'
    | '/site/$site/vms/'
    | '/site/$site/nodes/$node/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FleetRoute: typeof FleetRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof FleetRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/console': {
      id: '/settings/console'
      path: '/console'
      fullPath: '/settings/console'
      preLoaderRoute: typeof SettingsConsoleRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/site/': {
      id: '/site/'
      path: '/'
      fullPath: '/site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/fleet/nodes/': {
      id: '/fleet/nodes/'
      path: '/nodes'
      fullPath: '/fleet/nodes/'
      preLoaderRoute: typeof FleetNodesIndexRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/peers/': {
      id: '/fleet/peers/'
      path: '/peers'
      fullPath: '/fleet/peers/'
      preLoaderRoute: typeof FleetPeersIndexRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/tasks/': {
      id: '/fleet/tasks/'
      path: '/tasks'
      fullPath: '/fleet/tasks/'
      preLoaderRoute: typeof FleetTasksIndexRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/tasks/$task': {
      id: '/fleet/tasks/$task'
      path: '/tasks/$task'
      fullPath: '/fleet/tasks/$task'
      preLoaderRoute: typeof FleetTasksTaskRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/vms/': {
      id: '/fleet/vms/'
      path: '/vms'
      fullPath: '/fleet/vms/'
      preLoaderRoute: typeof FleetVmsIndexRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/vms/new': {
      id: '/fleet/vms/new'
      path: '/vms/new'
      fullPath: '/fleet/vms/new'
      preLoaderRoute: typeof FleetVmsNewRouteImport
      parentRoute: typeof FleetRoute
    }
    '/settings/connections/': {
      id: '/settings/connections/'
      path: '/'
      fullPath: '/settings/connections/'
      preLoaderRoute: typeof SettingsConnectionsIndexRouteImport
      parentRoute: typeof SettingsConnectionsRoute
    }
    '/settings/connections/$connection': {
      id: '/settings/connections/$connection'
      path: '/$connection'
      fullPath: '/settings/connections/$connection'
      preLoaderRoute: typeof SettingsConnectionsConnectionRouteImport
      parentRoute: typeof SettingsConnectionsRoute
    }
    '/site/$site/': {
      id: '/site/$site/'
      path: '/$site'
      fullPath: '/site/$site/'
      preLoaderRoute: typeof SiteSiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/fleet/nodes/$node/': {
      id: '/fleet/nodes/$node/'
      path: '/nodes/$node'
      fullPath: '/fleet/nodes/$node/'
      preLoaderRoute: typeof FleetNodesNodeIndexRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/peers/$peer/': {
      id: '/fleet/peers/$peer/'
      path: '/peers/$peer'
      fullPath: '/fleet/peers/$peer/'
      preLoaderRoute: typeof FleetPeersPeerIndexRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/vms/$vm/': {
      id: '/fleet/vms/$vm/'
      path: '/vms/$vm'
      fullPath: '/fleet/vms/$vm/'
      preLoaderRoute: typeof FleetVmsVmIndexRouteImport
      parentRoute: typeof FleetRoute
    }
    '/fleet/vms/$vm/edit': {
      id: '/fleet/vms/$vm/edit'
      path: '/vms/$vm/edit'
      fullPath: '/fleet/vms/$vm/edit'
      preLoaderRoute: typeof FleetVmsVmEditRouteImport
      parentRoute: typeof FleetRoute
    }
    '/site/$site/nodes/': {
      id: '/site/$site/nodes/'
      path: '/$site/nodes'
      fullPath: '/site/$site/nodes/'
      preLoaderRoute: typeof SiteSiteNodesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/$site/peers/': {
      id: '/site/$site/peers/'
      path: '/$site/peers'
      fullPath: '/site/$site/peers/'
      preLoaderRoute: typeof SiteSitePeersIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/$site/vms/': {
      id: '/site/$site/vms/'
      path: '/$site/vms'
      fullPath: '/site/$site/vms/'
      preLoaderRoute: typeof SiteSiteVmsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/$site/nodes/$node/': {
      id: '/site/$site/nodes/$node/'
      path: '/$site/nodes/$node'
      fullPath: '/site/$site/nodes/$node/'
      preLoaderRoute: typeof SiteSiteNodesNodeIndexRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface FleetRouteChildren {
  FleetIndexRoute: typeof FleetIndexRoute
  FleetTasksTaskRoute: typeof FleetTasksTaskRoute
  FleetVmsNewRoute: typeof FleetVmsNewRoute
  FleetNodesIndexRoute: typeof FleetNodesIndexRoute
  FleetPeersIndexRoute: typeof FleetPeersIndexRoute
  FleetTasksIndexRoute: typeof FleetTasksIndexRoute
  FleetVmsIndexRoute: typeof FleetVmsIndexRoute
  FleetVmsVmEditRoute: typeof FleetVmsVmEditRoute
  FleetNodesNodeIndexRoute: typeof FleetNodesNodeIndexRoute
  FleetPeersPeerIndexRoute: typeof FleetPeersPeerIndexRoute
  FleetVmsVmIndexRoute: typeof FleetVmsVmIndexRoute
}

const FleetRouteChildren: FleetRouteChildren = {
  FleetIndexRoute: FleetIndexRoute,
  FleetTasksTaskRoute: FleetTasksTaskRoute,
  FleetVmsNewRoute: FleetVmsNewRoute,
  FleetNodesIndexRoute: FleetNodesIndexRoute,
  FleetPeersIndexRoute: FleetPeersIndexRoute,
  FleetTasksIndexRoute: FleetTasksIndexRoute,
  FleetVmsIndexRoute: FleetVmsIndexRoute,
  FleetVmsVmEditRoute: FleetVmsVmEditRoute,
  FleetNodesNodeIndexRoute: FleetNodesNodeIndexRoute,
  FleetPeersPeerIndexRoute: FleetPeersPeerIndexRoute,
  FleetVmsVmIndexRoute: FleetVmsVmIndexRoute,
}

const FleetRouteWithChildren = FleetRoute._addFileChildren(FleetRouteChildren)

interface SettingsConnectionsRouteChildren {
  SettingsConnectionsConnectionRoute: typeof SettingsConnectionsConnectionRoute
  SettingsConnectionsIndexRoute: typeof SettingsConnectionsIndexRoute
}

const SettingsConnectionsRouteChildren: SettingsConnectionsRouteChildren = {
  SettingsConnectionsConnectionRoute: SettingsConnectionsConnectionRoute,
  SettingsConnectionsIndexRoute: SettingsConnectionsIndexRoute,
}

const SettingsConnectionsRouteWithChildren =
  SettingsConnectionsRoute._addFileChildren(SettingsConnectionsRouteChildren)

interface SettingsRouteChildren {
  SettingsConnectionsRoute: typeof SettingsConnectionsRouteWithChildren
  SettingsConsoleRoute: typeof SettingsConsoleRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsConnectionsRoute: SettingsConnectionsRouteWithChildren,
  SettingsConsoleRoute: SettingsConsoleRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteSiteIndexRoute: typeof SiteSiteIndexRoute
  SiteSiteNodesIndexRoute: typeof SiteSiteNodesIndexRoute
  SiteSitePeersIndexRoute: typeof SiteSitePeersIndexRoute
  SiteSiteVmsIndexRoute: typeof SiteSiteVmsIndexRoute
  SiteSiteNodesNodeIndexRoute: typeof SiteSiteNodesNodeIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteSiteIndexRoute: SiteSiteIndexRoute,
  SiteSiteNodesIndexRoute: SiteSiteNodesIndexRoute,
  SiteSitePeersIndexRoute: SiteSitePeersIndexRoute,
  SiteSiteVmsIndexRoute: SiteSiteVmsIndexRoute,
  SiteSiteNodesNodeIndexRoute: SiteSiteNodesNodeIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FleetRoute: FleetRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
